"""initial schema

Revision ID: 2bb7261b70dc
Revises: 
Create Date: 2026-07-17 17:39:56.162431
"""
from alembic import op
import sqlalchemy as sa


revision = '2bb7261b70dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('ref', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('decided_by', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_branch'), 'approvals', ['branch'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('tg_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('entity', sa.String(), nullable=True),
    sa.Column('ref', sa.String(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_ts'), 'audit_log', ['ts'], unique=False)
    op.create_table('branches',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('clock_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('employee', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('at_ts', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('pay_type', sa.String(), nullable=True),
    sa.Column('salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_branch'), 'employees', ['branch'], unique=False)
    op.create_table('ledger',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('account', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('employee', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('memo', sa.String(), nullable=True),
    sa.Column('entry_date', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_branch'), 'ledger', ['branch'], unique=False)
    op.create_index(op.f('ix_ledger_entry_date'), 'ledger', ['entry_date'], unique=False)
    op.create_table('link_codes',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('products',
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('min_level', sa.Integer(), nullable=True),
    sa.Column('uom', sa.String(), nullable=True),
    sa.Column('shelf', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('sku')
    )
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=False)
    op.create_table('purchases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('purchase_date', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchases_branch'), 'purchases', ['branch'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('from_branch', sa.String(), nullable=True),
    sa.Column('to_branch', sa.String(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movements',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('ref', sa.String(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('qty_before', sa.Integer(), nullable=True),
    sa.Column('qty_change', sa.Integer(), nullable=True),
    sa.Column('qty_after', sa.Integer(), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('moved_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['sku'], ['products.sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movements_branch'), 'movements', ['branch'], unique=False)
    op.create_index(op.f('ix_movements_moved_at'), 'movements', ['moved_at'], unique=False)
    op.create_index(op.f('ix_movements_sku'), 'movements', ['sku'], unique=False)
    op.create_table('stock',
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch'], ['branches.name'], ),
    sa.ForeignKeyConstraint(['sku'], ['products.sku'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sku', 'branch')
    )
    op.create_table('telegram_links',
    sa.Column('tg_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('device', sa.String(), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tg_id')
    )
    op.create_table('user_branches',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['branch'], ['branches.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'branch')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_branches')
    op.drop_table('telegram_links')
    op.drop_table('stock')
    op.drop_index(op.f('ix_movements_sku'), table_name='movements')
    op.drop_index(op.f('ix_movements_moved_at'), table_name='movements')
    op.drop_index(op.f('ix_movements_branch'), table_name='movements')
    op.drop_table('movements')
    op.drop_table('users')
    op.drop_table('transfers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_purchases_branch'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_table('products')
    op.drop_table('link_codes')
    op.drop_index(op.f('ix_ledger_entry_date'), table_name='ledger')
    op.drop_index(op.f('ix_ledger_branch'), table_name='ledger')
    op.drop_table('ledger')
    op.drop_index(op.f('ix_employees_branch'), table_name='employees')
    op.drop_table('employees')
    op.drop_table('customers')
    op.drop_table('clock_events')
    op.drop_table('branches')
    op.drop_index(op.f('ix_audit_log_ts'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_approvals_branch'), table_name='approvals')
    op.drop_table('approvals')
    # ### end Alembic commands ###
